### ISSUE TITLE
Acquia Recipe Database Connection

### ISSUE THREAD

**Issue by mikemadison13** [lando/acquia#15]
**Tell us about your setup**

I am currently running an Acquia BLT codebase and the drupal8 recipe. I have destroyed that VM and rebuilt using the experimental acquia recipe. As part of that process, I did update my database details to be 'acquia' across the board (vs. drupal8). What I am seeing is that with the drupal8 recipe, my setup works great. However, with the acquia recipe it cannot load my database setup. 

```
In Database.php line 371:
                                                             
  The specified database connection is not defined: default
```

BLT does have a number of overrides for settings files, so I'm wondering if the acquia recipe is somehow changing the way these are handled? It's highly suspicious to me that the exact same codebase works fine on the drupal8 recipe but not the acquia one.

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

lando version
v3.0.27

Mac OS 10.15.7

**Tell us about your `.lando.yml`**: 

see https://github.com/Drupal4Gov/Drupal-GovCon-2017/blob/develop/.lando.yml

See above, TLDR database connectivity works fine on drupal8 but not on acquia (and yes, I did update the database name, user name, and password to be acquia not drupal8). This appears to be flat out not finding the default database array.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

The govcon codebase can be spun up locally and works as is. You can use the same codebase to test the acquia recipe (although you'll have to update the database credentials and lando yml file)

**Comment by danepowell** [comment]
Following https://github.com/acquia/drupal-environment-detector/pull/16, BLT detects an Acquia Lando container as both an Acquia and Local environment. That's fine as such, but I don't see how it solves the problem because projects will first load the Acquia db credentials (which are correct), and then clobber them with the default local db credentials (which are wrong). @mikemadison13 did you work around this somehow?

**Comment by mikemadison13** [comment]
not exactly, i stoped using the acquia recipe due to performance issues. see https://github.com/lando/acquia/issues/10
