### ISSUE TITLE
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.29. in phar:///usr/local/bin/acli/vendor/composer/platform_check.php

### ISSUE THREAD

**Issue by keithdoyle9** [lando/acquia#44]
I have checked my dependencies over and over and none of them require PHP 8.0.2 or higher. They're all satisfiable by my current version 7.4.29. This just started happening.

**Comment by keithdoyle9** [comment]
`composer depends php
asm89/stack-cors                                1.3.0       requires  php (>=5.5.9)                   
brightcove/api                                  2.1         requires  php (>=7.1)                     
caxy/php-htmldiff                               v0.1.14     requires  php (>=7.3)                     
chi-teck/drupal-code-generator                  1.33.1      requires  php (>=5.5.9)                   
composer/semver                                 3.2.6       requires  php (^5.3.2 || ^7.0 || ^8.0)    
consolidation/annotated-command                 4.5.5       requires  php (>=7.1.3)                   
consolidation/config                            1.2.1       requires  php (>=5.4.0)                   
consolidation/filter-via-dot-access-data        1.0.0       requires  php (>=5.5.0)                   
consolidation/log                               2.1.1       requires  php (>=7.1.3)                   
consolidation/output-formatters                 4.2.2       requires  php (>=7.1.3)                   
consolidation/robo                              3.0.10      requires  php (>=7.1.3)                   
consolidation/self-update                       2.0.5       requires  php (>=5.5.0)                   
consolidation/site-alias                        3.1.5       requires  php (>=5.5.0)                   
consolidation/site-process                      4.2.0       requires  php (>=7.1.3)                   
cweagans/composer-patches                       1.7.2       requires  php (>=5.3.0)                   
cweagans/php-webdam-client                      1.0.1       requires  php (>=5.6.0)                   
dealerdirect/phpcodesniffer-composer-installer  v0.7.2      requires  php (>=5.3)                     
dflydev/dot-access-data                         v1.1.0      requires  php (>=5.3.2)                   
doctrine/annotations                            1.13.2      requires  php (^7.1 || ^8.0)              
doctrine/cache                                  1.12.1      requires  php (~7.1 || ^8.0)              
doctrine/collections                            1.6.8       requires  php (^7.1.3 || ^8.0)            
doctrine/common                                 2.13.3      requires  php (^7.1 || ^8.0)              
doctrine/event-manager                          1.1.1       requires  php (^7.1 || ^8.0)              
doctrine/inflector                              1.4.4       requires  php (^7.1 || ^8.0)              
doctrine/instantiator                           1.4.1       requires  php (^7.1 || ^8.0)              
doctrine/lexer                                  1.2.1       requires  php (^7.2 || ^8.0)              
doctrine/persistence                            1.3.8       requires  php (^7.1 || ^8.0)              
doctrine/reflection                             1.2.2       requires  php (^7.1 || ^8.0)              
drupal/brightcove                               3.0.0       requires  php (^7.3)                      
drupal/coder                                    8.3.15      requires  php (>=7.1)                     
drupal/core                                     9.3.13      requires  php (>=7.3.0)                   
drupal/core-composer-scaffold                   9.3.13      requires  php (>=7.3.0)                   
drupal/core-project-message                     9.3.13      requires  php (>=7.3.0)                   
drupal/dynamic_entity_reference                 1.16.0      requires  php (>=7.4)                     
drupal/inline_entity_form                       1.0.0-rc11  requires  php (>=7.1)                     
drupal/metatag                                  1.19.0      requires  php (>=7.0)                     
drupal/scheduled_transitions                    2.2.1       requires  php (>=7.4)                     
drupal/twig_tweak                               3.1.3       requires  php (>=7.3)                     
drush/drush                                     10.6.2      requires  php (>=7.1.3)                   
egulias/email-validator                         3.1.2       requires  php (>=7.2)                     
enlightn/security-checker                       v1.10.0     requires  php (>=5.6)                     
enshrined/svg-sanitize                          0.15.4      requires  php (^7.0 || ^8.0)              
ezyang/htmlpurifier                             v4.14.0     requires  php (>=5.2)                     
fileeye/mimemap                                 1.2.2       requires  php (>=5.6)                     
grasmash/expander                               1.0.0       requires  php (>=5.4)                     
grasmash/yaml-expander                          1.4.0       requires  php (>=5.4)                     
guzzlehttp/guzzle                               6.5.5       requires  php (>=5.5)                     
guzzlehttp/promises                             1.5.1       requires  php (>=5.5)                     
guzzlehttp/psr7                                 1.8.5       requires  php (>=5.4.0)                   
laminas/laminas-diactoros                       2.8.0       requires  php (^7.3 || ~8.0.0 || ~8.1.0)  
laminas/laminas-escaper                         2.9.0       requires  php (^7.3 || ~8.0.0 || ~8.1.0)  
laminas/laminas-feed                            2.15.0      requires  php (^7.3 || ~8.0.0 || ~8.1.0)  
laminas/laminas-stdlib                          3.6.1       requires  php (^7.3 || ~8.0.0 || ~8.1.0)  
league/container                                3.4.1       requires  php (^7.0 || ^8.0)              
lsolesen/pel                                    0.9.12      requires  php (>=7.1.0)                   
masterminds/html5                               2.7.5       requires  php (>=5.3.0)                   
mkalkbrenner/php-htmldiff-advanced              0.0.8       requires  php (>=5.5.0)                   
myclabs/deep-copy                               1.11.0      requires  php (^7.1 || ^8.0)              
nikic/php-parser                                v4.13.2     requires  php (>=7.0)                     
pear/archive_tar                                1.4.14      requires  php (>=5.2.0)                   
pear/pear_exception                             v1.0.2      requires  php (>=5.2.0)                   
phar-io/manifest                                2.0.3       requires  php (^7.2 || ^8.0)              
phar-io/version                                 3.2.1       requires  php (^7.2 || ^8.0)              
phpdocumentor/reflection-common                 2.2.0       requires  php (^7.2 || ^8.0)              
phpdocumentor/reflection-docblock               5.3.0       requires  php (^7.2 || ^8.0)              
phpdocumentor/type-resolver                     1.6.1       requires  php (^7.2 || ^8.0)              
phpspec/prophecy                                v1.15.0     requires  php (^7.2 || ~8.0, <8.2)        
phpstan/phpdoc-parser                           1.5.1       requires  php (^7.2 || ^8.0)              
phpunit/php-code-coverage                       9.2.15      requires  php (>=7.3)                     
phpunit/php-file-iterator                       3.0.6       requires  php (>=7.3)                     
phpunit/php-invoker                             3.1.1       requires  php (>=7.3)                     
phpunit/php-text-template                       2.0.4       requires  php (>=7.3)                     
phpunit/php-timer                               5.0.3       requires  php (>=7.3)                     
phpunit/phpunit                                 9.5.20      requires  php (>=7.3)                     
psr/cache                                       1.0.1       requires  php (>=5.3.0)                   
psr/container                                   1.1.1       requires  php (>=7.2.0)                   
psr/http-factory                                1.0.1       requires  php (>=7.0.0)                   
psr/http-message                                1.0.1       requires  php (>=5.3.0)                   
psr/log                                         1.1.4       requires  php (>=5.3.0)                   
psy/psysh                                       v0.10.12    requires  php (^8.0 || ^7.0 || ^5.5.9)    
ralouphie/getallheaders                         3.0.3       requires  php (>=5.6)                     
sebastian/cli-parser                            1.0.1       requires  php (>=7.3)                     
sebastian/code-unit                             1.0.8       requires  php (>=7.3)                     
sebastian/code-unit-reverse-lookup              2.0.3       requires  php (>=7.3)                     
sebastian/comparator                            4.0.6       requires  php (>=7.3)                     
sebastian/complexity                            2.0.2       requires  php (>=7.3)                     
sebastian/diff                                  4.0.4       requires  php (>=7.3)                     
sebastian/environment                           5.1.4       requires  php (>=7.3)                     
sebastian/exporter                              4.0.4       requires  php (>=7.3)                     
sebastian/global-state                          5.0.5       requires  php (>=7.3)                     
sebastian/lines-of-code                         1.0.3       requires  php (>=7.3)                     
sebastian/object-enumerator                     4.0.4       requires  php (>=7.3)                     
sebastian/object-reflector                      2.0.4       requires  php (>=7.3)                     
sebastian/recursion-context                     4.0.4       requires  php (>=7.3)                     
sebastian/resource-operations                   3.0.3       requires  php (>=7.3)                     
sebastian/type                                  3.0.0       requires  php (>=7.3)                     
sebastian/version                               3.0.2       requires  php (>=7.3)                     
sirbrillig/phpcs-variable-analysis              v2.11.3     requires  php (>=5.4.0)                   
slevomat/coding-standard                        7.2.0       requires  php (^7.2 || ^8.0)              
squizlabs/php_codesniffer                       3.6.2       requires  php (>=5.4.0)                   
stack/builder                                   v1.0.6      requires  php (>=7.2.0)                   
symfony-cmf/routing                             2.3.4       requires  php (^7.2 || ^8.0)              
symfony/console                                 v4.4.34     requires  php (>=7.1.3)                   
symfony/debug                                   v4.4.31     requires  php (>=7.1.3)                   
symfony/dependency-injection                    v4.4.34     requires  php (>=7.1.3)                   
symfony/deprecation-contracts                   v2.5.0      requires  php (>=7.1)                     
symfony/error-handler                           v4.4.34     requires  php (>=7.1.3)                   
symfony/event-dispatcher                        v4.4.34     requires  php (>=7.1.3)                   
symfony/event-dispatcher-contracts              v1.1.11     requires  php (>=7.1.3)                   
symfony/filesystem                              v4.4.39     requires  php (>=7.1.3)                   
symfony/finder                                  v5.4.8      requires  php (>=7.2.5)                   
symfony/http-client-contracts                   v2.5.0      requires  php (>=7.2.5)                   
symfony/http-foundation                         v4.4.34     requires  php (>=7.1.3)                   
symfony/http-kernel                             v4.4.35     requires  php (>=7.1.3)                   
symfony/mime                                    v5.4.0      requires  php (>=7.2.5)                   
symfony/polyfill-ctype                          v1.23.0     requires  php (>=7.1)                     
symfony/polyfill-iconv                          v1.23.0     requires  php (>=7.1)                     
symfony/polyfill-intl-idn                       v1.23.0     requires  php (>=7.1)                     
symfony/polyfill-intl-normalizer                v1.23.0     requires  php (>=7.1)                     
symfony/polyfill-mbstring                       v1.23.1     requires  php (>=7.1)                     
symfony/polyfill-php72                          v1.25.0     requires  php (>=7.1)                     
symfony/polyfill-php73                          v1.25.0     requires  php (>=7.1)                     
symfony/polyfill-php80                          v1.23.1     requires  php (>=7.1)                     
symfony/process                                 v4.4.35     requires  php (>=7.1.3)                   
symfony/psr-http-message-bridge                 v2.1.2      requires  php (>=7.1)                     
symfony/routing                                 v4.4.34     requires  php (>=7.1.3)                   
symfony/serializer                              v4.4.35     requires  php (>=7.1.3)                   
symfony/service-contracts                       v2.5.0      requires  php (>=7.2.5)                   
symfony/translation                             v4.4.34     requires  php (>=7.1.3)                   
symfony/translation-contracts                   v2.5.0      requires  php (>=7.2.5)                   
symfony/validator                               v4.4.35     requires  php (>=7.1.3)                   
symfony/var-dumper                              v5.4.0      requires  php (>=7.2.5)                   
symfony/yaml                                    v4.4.34     requires  php (>=7.1.3)                   
theseer/tokenizer                               1.2.1       requires  php (^7.2 || ^8.0)              
twig/twig                                       v2.14.11    requires  php (>=7.1.3)                   
typo3/phar-stream-wrapper                       v3.1.7      requires  php (^7.0 || ^8.0)              
webmozart/assert                                1.10.0      requires  php (^7.2 || ^8.0)              
webmozart/path-util                             2.3.0       requires  php (>=5.3.3)`

**Comment by rubenvarela** [comment]
Can you check if it's ACLI, #43

**Comment by rubenvarela** [comment]
```
recipe: acquia
config:
  acli_version: 1.3.1
```
or maybe 1.3.0

**Comment by labboy0276** [comment]
@rubenvarela @keithdoyle9 Yes, this is due to the 2.x version of ACLI requiring PHP 8.0.

Just pin the recipe to the [last version of 1.x](https://github.com/acquia/cli/releases), which is `1.30.1`

**Comment by keithdoyle9** [comment]
That worked, thank you!
