### ISSUE TITLE
Lando Pull / ACLI Pull and multisites

### ISSUE THREAD

**Issue by drogers98** [lando/acquia#76]
Using the multisite approach defined on [lando docs](https://docs.lando.dev/drupal/drupal-multisite.html), ie, creating proxies for each multisite, there seems to be no way I can find to specify a Host in either the ACLI or Lando pull commands. This all means, I cannot automate pulling databases from acquia into a specific site, of a multisite install, afaik.

We used to work around this with a drush sql export/download, and a `lando db-import`, however, Acquia cloud next seems to have made doing that no longer feasable (cant seem to run a drush sql export/download anymore, per acquias docs).

Additionally, the closest ACLI operation to a SQL download, `ACLI pull:db` does not let you specify either a file name or location when using the `--no-import` flag, which would then allow us to import via `lando db-import MY_FILE.sql --host MYSITE` or similar, easily.

All this is to say, using multisites with acquia and lando is still extremely problematic, unless I am missing something here.

Is there a way, or any plans to allow the setting of `host` for these commands?

**Comment by rubenvarela** [comment]
You're right that acli can't do it automatically/easily (which is what lando pull uses, check`lando acli pull`)

I've dug into it in the past. You can use the api, `lando acli api:list`, to get the databases, then the urls, then download, extract, and import it. But you'll still require a mapping table.

Having said that, imo, the best way I've found out to do this is via `drush` and aliases.

`drush sql-sync @site1 @site1-local`, https://www.drush.org/12.x/commands/sql_sync/. Specify these and let it run.

If interested in the api via acli, you'll need,

 - `lando acli api:applications:database-list`
 - `lando acli api:environments:database-backup-list APPLICATION_NAME.ENV DATABASE_NAME_FROM_PREVIOUS`
 - `lando acli api:environments:database-backup-download APPLICATION_NAME.ENV DATABASE_NAME_FROM_ABOVE BACKUP_ID`
 - wget/curl `url`
 - extract
 - then import into the right database

**Comment by m435tr0d** [comment]
Check out this recipe which may help: https://github.com/nalipaz/lando-acquia-multisite-recipe

**Comment by reynoldsalec** [comment]
Some good tips on this issue, @drogers98 feel free to follow-up here if you have further questions (or go to the Lando Slack), going to close this out for the time being.
